/* MAHALCO Hebrew tool guide. Drop this script on any page; URLs resolve from the script. */
(() => {
  'use strict';
  if (document.querySelector('mahalco-car-guide')) return;
  const base = new URL('../', document.currentScript.src);
  const host = document.createElement('mahalco-car-guide');
  document.body.append(host);
  const root = host.attachShadow({mode:'open'});
  root.innerHTML = `<style>
:host{all:initial;position:fixed;left:20px;bottom:24px;z-index:10000;font-family:Arial,sans-serif;color:#E7E8E3;direction:rtl;--gold:#E9B12F}
*{box-sizing:border-box}button,input{font:inherit}button,a,input{touch-action:manipulation}button{cursor:pointer}button:focus-visible,a:focus-visible,input:focus-visible{outline:3px solid var(--gold);outline-offset:3px}[hidden]{display:none!important}
.dock{width:136px;text-align:center}.car{padding:0;border:0;background:transparent;width:136px;height:116px;display:block;cursor:grab;touch-action:none;filter:drop-shadow(0 7px 8px #0005)}.car:active{cursor:grabbing}.car img{width:100%;height:100%;object-fit:contain;pointer-events:none;user-select:none}.controls{display:flex;justify-content:center;align-items:center;gap:0;width:112px;margin:auto;background:#23272cf5;border:1px solid #62666b;border-radius:40px;box-shadow:0 5px 18px #0003}.controls button{background:none;color:#f1f2ee;border:0;min-width:48px;height:42px;display:grid;place-items:center}.controls button+button{border-inline-start:1px solid #62666b}.controls svg{width:22px;height:22px}.controls button:hover{color:var(--gold)}.listening{color:var(--gold)!important;animation:pulse 1s infinite}
.panel{position:fixed;display:flex;flex-direction:column;width:360px;max-width:calc(100vw - 24px);height:480px;max-height:calc(100dvh - 28px);border:1px solid #4b535b;border-radius:22px;background:#23272C;box-shadow:0 20px 65px #0005;overflow:hidden;text-align:right;font-size:16px;line-height:1.6}.header{padding:16px 18px;border-bottom:1px solid #434a52;display:flex;align-items:center;gap:10px}.header strong{font-size:18px;display:block}.header small{display:block;color:#c6c9c1;font-size:13px}.header .mini{width:48px;height:48px;object-fit:contain}.close{margin-inline-start:auto;border:0;background:#353c43;color:#fff;border-radius:50%;width:32px;height:32px;font-size:23px}.messages{flex:1;overflow:auto;overscroll-behavior:contain;padding:18px;display:flex;flex-direction:column;gap:12px}.bubble{background:#323940;padding:12px 14px;border-radius:16px 4px 16px 16px;overflow-wrap:anywhere}.user{background:#E9B12F;color:#141A1F;align-self:flex-start;max-width:90%;border-radius:4px 16px 16px 16px}.results{display:grid;gap:8px;margin-top:12px}.result{display:block;padding:10px 12px;border:1px solid #687079;border-radius:10px;color:#fff;text-decoration:none;font-size:15px}.result:hover{border-color:var(--gold);background:#424b54}.result b{color:#f5c453;display:block}.result span{font-size:13px;display:block}.quick{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.quick button{background:#23272c;color:#f5c453;border:1px solid #79705a;border-radius:20px;padding:6px 12px;font-size:14px}.footer{padding:12px;border-top:1px solid #434a52}.form{display:flex;gap:7px}.form input{min-width:0;flex:1;border:1px solid #687079;background:#171d22;color:#fff;border-radius:12px;padding:10px;font-size:16px}.form button{border:0;background:var(--gold);color:#141a1f;border-radius:12px;padding:8px 13px;font-weight:bold}.tools{display:flex;gap:12px;flex-wrap:wrap;margin-top:8px}.tools button{border:0;background:none;color:#c6c9c1;font-size:13px;padding:3px}.status{font-size:13px;color:#f5c453;min-height:20px;margin:6px 0 0}.restore{border:1px solid #62666b;border-radius:25px;background:#23272c;color:#f5c453;padding:9px 14px;white-space:nowrap}
/* Animate only the artwork: drag targets and controls stay still. */
.car img,.mini{transform-origin:50% 82%;animation:car-idle 3.8s ease-in-out infinite;will-change:transform}
.car:hover img,.car:focus-visible img{animation:car-greet .75s ease-in-out infinite}
:host(.car-react) .car img,:host(.car-react) .mini{animation:car-greet .65s ease-in-out 2}
:host(.car-listening) .car img,:host(.car-listening) .mini{animation:car-listen 1.15s ease-in-out infinite;filter:drop-shadow(0 0 5px #e9b12f80)}
:host(.car-speaking) .car img,:host(.car-speaking) .mini{animation:car-talk .48s ease-in-out infinite}
:host(.car-dragging) .car img{animation:car-drive .24s ease-in-out infinite}
:host(.motion-off) .car img,:host(.motion-off) .mini{animation:none;will-change:auto}
@keyframes car-idle{0%,100%{transform:translateY(0) rotate(-1deg)}45%{transform:translateY(-5px) rotate(1.5deg)}65%{transform:translateY(-3px) rotate(.5deg)}}
@keyframes car-greet{0%,100%{transform:translateY(0) rotate(0)}30%{transform:translateY(-9px) rotate(-5deg)}65%{transform:translateY(-3px) rotate(4deg)}}
@keyframes car-listen{0%,100%{transform:translateY(-2px) rotate(-3deg) scale(1.02)}50%{transform:translateY(-6px) rotate(2deg) scale(1.055)}}
@keyframes car-talk{0%,100%{transform:translateY(0) rotate(-1.5deg)}50%{transform:translateY(-4px) rotate(1.5deg)}}
@keyframes car-drive{0%,100%{transform:translateY(-3px) rotate(-5deg)}50%{transform:translateY(-5px) rotate(-4deg)}}
@keyframes pulse{50%{opacity:.4}}@media(prefers-reduced-motion:reduce){*{animation:none!important}}@media print{:host{display:none}}
</style><div class="dock"><button class="car" aria-label="פתיחת מדריך הכלים. גררו לשינוי מיקום, או השתמשו במקשי החצים." title="גררו אותי לכל מקום"><img alt="מכונית העזרה של MAHALCO" draggable="false"></button><div class="controls"><button class="chat" aria-label="כתיבה למדריך הכלים" aria-expanded="false"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M10 4H5a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2h13a2 2 0 0 0 2-2v-5M15 3l6 6M8 16l2-6L18 2l4 4-8 8z"/></svg></button><button class="voice" aria-label="חיפוש קולי בעברית"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"><path d="M4 10v4M8 6v12M12 3v18M16 7v10M20 10v4"/></svg></button></div></div><button class="restore" hidden aria-label="הצגת מכונית העזרה">עזרה בדרך</button><section class="panel" hidden role="dialog" aria-label="מדריך הכלים של MAHALCO" dir="rtl"><div class="header"><img class="mini" alt=""><div><strong>לאן מתקדמים?</strong><small>מדריך הכלים של MAHALCO</small></div><button class="close" aria-label="סגירה">×</button></div><div class="messages" role="log" aria-live="polite" aria-relevant="additions"></div><div class="footer"><form class="form"><input aria-label="מה תרצו למצוא?" placeholder="למשל: חניה, צמתים או חתכים…" maxlength="300" autocomplete="off"><button type="submit">שליחה</button></form><p class="status" role="status"></p><div class="tools"><button class="voice panel-voice" aria-label="חיפוש קולי בעברית">חיפוש קולי</button><button class="read" aria-pressed="false">הקראה: כבויה</button><button class="reset">שיחה חדשה</button><button class="motion" aria-pressed="true">אנימציה: פעילה</button><button class="position">איפוס מיקום</button><button class="hide">מזעור המכונית</button></div></div></section>`;
  const $ = s => root.querySelector(s);
  root.querySelectorAll('img').forEach(img => img.src = new URL('assets/car-guide/car.png',base).href);
  const panel=$('.panel'), input=$('input'), log=$('.messages'), car=$('.car');
  let catalog=[], catalogFailed=false, listening=false, recognition, read=false, lastReply='', moved=false;
  const catalogReady=fetch(new URL('assets/car-guide/catalog.json',base)).then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{catalog=data}).catch(()=>{catalogFailed=true});
  const storage={get(k){try{return localStorage.getItem('mh-car-'+k)}catch{return null}},set(k,v){try{localStorage.setItem('mh-car-'+k,v)}catch{}}};
  let reactionTimer;
  function react(){clearTimeout(reactionTimer);host.classList.remove('car-react');void car.offsetWidth;host.classList.add('car-react');reactionTimer=setTimeout(()=>host.classList.remove('car-react'),1300)}
  const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
  let motionEnabled=storage.get('motion')!=='off';
  function syncMotion(){const active=motionEnabled&&!reducedMotion.matches;host.classList.toggle('motion-off',!active);$('.motion').textContent=reducedMotion.matches?'אנימציה: מופחתת':'אנימציה: '+(active?'פעילה':'כבויה');$('.motion').setAttribute('aria-pressed',String(active));$('.motion').disabled=reducedMotion.matches}
  $('.motion').onclick=()=>{motionEnabled=!motionEnabled;storage.set('motion',motionEnabled?'on':'off');syncMotion()};reducedMotion.addEventListener('change',syncMotion);syncMotion();
  function place(x,y){const w=host.offsetWidth||136,h=host.offsetHeight||158;host.style.left=Math.max(8,Math.min(innerWidth-w-8,x))+'px';host.style.top=Math.max(8,Math.min(innerHeight-h-8,y))+'px';host.style.bottom='auto';positionPanel()}
  function positionPanel(){if(panel.hidden)return;const r=host.getBoundingClientRect(),w=panel.offsetWidth,h=panel.offsetHeight;panel.style.left=Math.max(12,Math.min(innerWidth-w-12,r.right+w+24<=innerWidth?r.right+12:r.left-w-12))+'px';panel.style.top=Math.max(12,Math.min(innerHeight-h-12,r.bottom-h))+'px'}
  function savePosition(){const r=host.getBoundingClientRect();storage.set('position',JSON.stringify({x:r.left,y:r.top}))}
  try{const p=JSON.parse(storage.get('position'));if(p&&Number.isFinite(p.x)&&Number.isFinite(p.y))place(p.x,p.y)}catch{}
  function open(){if(panel.hidden)react();panel.hidden=false;$('.chat').setAttribute('aria-expanded','true');positionPanel();input.focus()}
  function close(){panel.hidden=true;$('.chat').setAttribute('aria-expanded','false');stopVoice();if(read)speechSynthesis.cancel();host.classList.remove('car-speaking');$('.chat').focus()}
  function bubble(text,user=false){const el=document.createElement('div');el.className='bubble'+(user?' user':'');el.textContent=text;log.append(el);while(log.children.length>30)log.firstChild.remove();log.scrollTop=log.scrollHeight;return el}
  function speak(text){if(!read||!('speechSynthesis'in window))return;speechSynthesis.cancel();host.classList.remove('car-speaking');const u=new SpeechSynthesisUtterance(text);u.lang='he-IL';u.onstart=()=>host.classList.add('car-speaking');u.onend=u.onerror=()=>host.classList.remove('car-speaking');speechSynthesis.speak(u)}
  function welcome(){log.replaceChildren();const el=bubble('שלום! אני כאן כדי לעזור למצוא את הכלי המתאים באתר. מה תרצו לתכנן או לבדוק?');const quick=document.createElement('div');quick.className='quick';['חניה','צמתים','חתכים','מרחק ראייה'].forEach(t=>{const b=document.createElement('button');b.textContent=t;b.onclick=()=>ask(t);quick.append(b)});el.append(quick)}
  const normalize=s=>s.toLowerCase().replace(/[״"׳'?,.!؟]/g,' ').replace(/\s+/g,' ').trim();
  async function ask(text){text=text.trim().slice(0,300);if(!text)return;bubble(text,true);input.value='';await catalogReady;
    const words=normalize(text).split(' ').filter(w=>w.length>1&&!['אני','צריך','צריכה','רוצה','של','את','לי','איך','איפה','אפשר','למצוא','כלי','שלום','היי'].includes(w));
    const matches=catalog.map(item=>{const hay=normalize(item.title+' '+item.description+' '+(item.keywords||''));return{...item,score:words.reduce((sum,w)=>sum+((hay.includes(w)||(w.length>3&&/^[לבמהו]/.test(w)&&hay.includes(w.slice(1))))?(normalize(item.title).includes(w)?3:1):0),0)}}).filter(i=>i.score>0).sort((a,b)=>b.score-a.score).slice(0,4);
    lastReply=matches.length?'מצאתי כלים שיכולים להתאים. בחרו כלי כדי לפתוח אותו:':catalogFailed?'לא הצלחתי לטעון את רשימת הכלים. אפשר לפתוח את הקטלוג או לנסות שוב לאחר רענון.':'לא מצאתי התאמה. נסו מונח כמו חניה, צומת, חתך, תור או ראייה.';
    const el=bubble(lastReply), links=document.createElement('div');links.className='results';
    (matches.length?matches:[{title:'פתיחת קטלוג הכלים',description:'כל כלי MAHALCO במקום אחד',url:'index.html#catalog'}]).forEach(item=>{const a=document.createElement('a');a.className='result';const url=new URL(item.url,base);if(!['http:','https:'].includes(url.protocol))return;a.href=url.href;const b=document.createElement('b'),s=document.createElement('span');b.textContent=item.title;s.textContent=item.description;a.append(b,s);links.append(a)});el.append(links);log.scrollTop=log.scrollHeight;react();speak(lastReply+(matches.length?' '+matches.map(m=>m.title).join('. '):''))}
  $('.form').onsubmit=e=>{e.preventDefault();ask(input.value)};$('.chat').onclick=()=>panel.hidden?open():close();$('.close').onclick=close;
  $('.reset').onclick=()=>{if('speechSynthesis'in window)speechSynthesis.cancel();host.classList.remove('car-speaking');stopVoice();welcome();input.focus()};$('.position').onclick=()=>{place(20,innerHeight-190);savePosition()};
  $('.hide').onclick=()=>{close();$('.dock').hidden=true;$('.restore').hidden=false;storage.set('minimized','1');place(host.offsetLeft,host.offsetTop);$('.restore').focus()};
  $('.restore').onclick=()=>{$('.dock').hidden=false;$('.restore').hidden=true;storage.set('minimized','0');place(host.offsetLeft,host.offsetTop);open()};
  if(storage.get('minimized')==='1'){$('.dock').hidden=true;$('.restore').hidden=false}
  $('.read').onclick=()=>{if(!('speechSynthesis'in window)){$('.status').textContent='הדפדפן אינו תומך בהקראה.';return}read=!read;$('.read').textContent='הקראה: '+(read?'פעילה':'כבויה');$('.read').setAttribute('aria-pressed',String(read));if(read)speak(lastReply||'שלום, מה תרצו למצוא?');else speechSynthesis.cancel()};
  function stopVoice(){if(recognition)recognition.abort();listening=false;host.classList.remove('car-listening');root.querySelectorAll('.voice').forEach(b=>{b.classList.remove('listening');b.setAttribute('aria-label','חיפוש קולי בעברית')})}
  function toggleVoice(){open();if(listening){stopVoice();$('.status').textContent='ההאזנה הופסקה.';return}const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech){$('.status').textContent='חיפוש קולי אינו נתמך בדפדפן זה. אפשר להקליד כאן.';return}recognition=new Speech();recognition.lang='he-IL';recognition.interimResults=false;recognition.maxAlternatives=1;recognition.onstart=()=>{listening=true;host.classList.add('car-listening');root.querySelectorAll('.voice').forEach(b=>{b.classList.add('listening');b.setAttribute('aria-label','הפסקת האזנה')});$('.status').textContent='מקשיב… הדיבור מעובד בשירות הזיהוי של הדפדפן.'};recognition.onresult=e=>{const t=e.results[0][0].transcript;input.value=t;$('.status').textContent='הטקסט מוכן. לחצו שליחה לחיפוש.';input.focus()};recognition.onerror=e=>{$('.status').textContent=e.error==='not-allowed'?'אין הרשאה למיקרופון. אפשר להקליד או לאפשר גישה בדפדפן.':e.error==='aborted'?'ההאזנה הופסקה.':'לא הצלחתי לשמוע. נסו שוב או הקלידו.'};recognition.onend=()=>{listening=false;host.classList.remove('car-listening');root.querySelectorAll('.voice').forEach(b=>{b.classList.remove('listening');b.setAttribute('aria-label','חיפוש קולי בעברית')})};try{recognition.start()}catch{$('.status').textContent='לא ניתן להפעיל את המיקרופון. אפשר להקליד.'}};
  root.querySelectorAll('.voice').forEach(b=>b.onclick=toggleVoice);
  let drag=null;car.onpointerdown=e=>{if(e.button!==0)return;const r=host.getBoundingClientRect();drag={x:e.clientX,y:e.clientY,left:r.left,top:r.top};moved=false;car.setPointerCapture(e.pointerId)};car.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>5)moved=true;if(moved){host.classList.add('car-dragging');place(drag.left+dx,drag.top+dy)}};car.onpointerup=()=>{host.classList.remove('car-dragging');if(moved)savePosition();drag=null};car.onpointercancel=()=>{host.classList.remove('car-dragging');drag=null;moved=true};car.onclick=()=>{if(!moved)panel.hidden?open():close();moved=false};car.onkeydown=e=>{const directions={ArrowLeft:[-20,0],ArrowRight:[20,0],ArrowUp:[0,-20],ArrowDown:[0,20]};if(directions[e.key]){e.preventDefault();const r=host.getBoundingClientRect(),d=directions[e.key];place(r.left+d[0],r.top+d[1]);savePosition()}};
  root.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden){e.preventDefault();close()}});window.addEventListener('resize',()=>{const r=host.getBoundingClientRect();place(r.left,r.top)});welcome();
})();
