/* MAHALCO Hebrew tool guide. Drop this script on any page; URLs resolve from the script. */
(() => {
  'use strict';
  if (document.querySelector('mahalco-car-guide')) return;
  const base = new URL('../', document.currentScript.src);
  const host = document.createElement('mahalco-car-guide');
  document.body.append(host);
  const root = host.attachShadow({mode:'open'});
  root.innerHTML = `<style>
:host{all:initial;position:fixed;left:20px;bottom:24px;z-index:2147483000;font-family:Arial,sans-serif;color:#E7E8E3;direction:rtl;--gold:#E9B12F}
*{box-sizing:border-box}button,input{font:inherit}button,a,input{touch-action:manipulation}button{cursor:pointer}button:focus-visible,a:focus-visible,input:focus-visible{outline:3px solid var(--gold);outline-offset:3px}[hidden]{display:none!important}
.dock{width:136px;text-align:center}.car{padding:0;border:0;background:transparent;width:136px;height:116px;display:block;cursor:grab;touch-action:none;filter:drop-shadow(0 7px 8px #0005)}.car:active{cursor:grabbing}.car img{width:100%;height:100%;object-fit:contain;pointer-events:none;user-select:none}.controls{display:flex;justify-content:center;align-items:center;gap:0;width:112px;margin:auto;background:#23272cf5;border:1px solid #62666b;border-radius:40px;box-shadow:0 5px 18px #0003}.controls button{background:none;color:#f1f2ee;border:0;min-width:48px;height:42px;display:grid;place-items:center}.controls button+button{border-inline-start:1px solid #62666b}.controls svg{width:22px;height:22px}.controls button:hover{color:var(--gold)}.listening{color:var(--gold)!important;animation:pulse 1s infinite}
.panel{position:fixed;display:flex;flex-direction:column;width:360px;max-width:calc(100vw - 24px);height:480px;max-height:calc(100dvh - 28px);border:1px solid #4b535b;border-radius:22px;background:#23272C;box-shadow:0 20px 65px #0005;overflow:hidden;text-align:right;font-size:16px;line-height:1.6}.header{padding:16px 18px;border-bottom:1px solid #434a52;display:flex;align-items:center;gap:10px}.header strong{font-size:18px;display:block}.header small{display:block;color:#c6c9c1;font-size:13px}.header .mini{width:48px;height:48px;object-fit:contain}.close{margin-inline-start:auto;border:0;background:#353c43;color:#fff;border-radius:50%;width:32px;height:32px;font-size:23px}.messages{flex:1;overflow:auto;overscroll-behavior:contain;padding:18px;display:flex;flex-direction:column;gap:12px}.bubble{background:#323940;padding:12px 14px;border-radius:16px 4px 16px 16px;overflow-wrap:anywhere}.user{background:#E9B12F;color:#141A1F;align-self:flex-start;max-width:90%;border-radius:4px 16px 16px 16px}.results{display:grid;gap:8px;margin-top:12px}.result{display:block;padding:10px 12px;border:1px solid #687079;border-radius:10px;color:#fff;text-decoration:none;font-size:15px}.result:hover{border-color:var(--gold);background:#424b54}.result b{color:#f5c453;display:block}.result span{font-size:13px;display:block}.quick{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.quick button{background:#23272c;color:#f5c453;border:1px solid #79705a;border-radius:20px;padding:6px 12px;font-size:14px}.footer{padding:12px;border-top:1px solid #434a52}.form{display:flex;gap:7px}.form input{min-width:0;flex:1;border:1px solid #687079;background:#171d22;color:#fff;border-radius:12px;padding:10px;font-size:16px}.form button{border:0;background:var(--gold);color:#141a1f;border-radius:12px;padding:8px 13px;font-weight:bold}.tools{display:flex;gap:12px;flex-wrap:wrap;margin-top:8px}.tools button{border:0;background:none;color:#c6c9c1;font-size:13px;padding:3px}.status{font-size:13px;color:#f5c453;min-height:20px;margin:6px 0 0}.restore{display:flex;align-items:center;gap:2px;border:1px solid #62666b;border-top:0;border-radius:0 0 14px 14px;background:#23272cf2;color:#f5c453;padding:6px 10px 2px;min-width:56px;white-space:nowrap;box-shadow:0 4px 12px #0004;transform:translateY(-6px);transition:transform .2s ease}.restore:hover,.restore:focus-visible{transform:translateY(0)}.restore img{width:24px;height:18px;object-fit:contain;pointer-events:none}.restore svg{width:12px;height:12px}
:host(.parked){top:0!important;bottom:auto!important}
.dock.drop{animation:drop .45s cubic-bezier(.2,.9,.3,1.25)}@keyframes drop{from{transform:translateY(-110vh)}to{transform:none}}
/* One continuous pose avoids jumps when listening, greeting or dragging changes. */
.art{display:block;position:relative;width:116px;height:116px;margin:auto;pointer-events:none;transform-origin:50% 82%;transform:translate3d(0,var(--car-y,0px),0) rotate(var(--car-lean,0deg));will-change:transform}
.art img{display:block;width:100%;height:100%;object-fit:contain}.header .mini{width:48px;height:48px;margin:0;flex-shrink:0}
.face{position:absolute;inset:0;width:100%;height:100%;overflow:visible}.eye{transform-box:fill-box;transform-origin:center;transform:scaleY(var(--eye-open,1))}.pupil{transform:translate(var(--gaze-x,0px),var(--gaze-y,0px))}
:host(.car-listening) .face{filter:drop-shadow(0 0 12px #e9b12f88)}
:host(.motion-off) .art{transform:none;will-change:auto}:host(.motion-off) .eye,:host(.motion-off) .pupil{transform:none}
@keyframes pulse{50%{opacity:.4}}@media(prefers-reduced-motion:reduce){*{animation:none!important}}@media print{:host{display:none}}
</style><div class="dock" hidden><button class="car" aria-label="פתיחת מדריך הכלים. גררו לשינוי מיקום, או השתמשו במקשי החצים." title="גררו אותי לכל מקום"><span class="art"><img alt="מכונית העזרה של MAHALCO" draggable="false"></span></button><div class="controls"><button class="chat" aria-label="כתיבה למדריך הכלים" aria-expanded="false"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M10 4H5a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2h13a2 2 0 0 0 2-2v-5M15 3l6 6M8 16l2-6L18 2l4 4-8 8z"/></svg></button><button class="voice" aria-label="חיפוש קולי בעברית"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"><path d="M4 10v4M8 6v12M12 3v18M16 7v10M20 10v4"/></svg></button></div></div><button class="restore" aria-label="פתיחת מכונית העזרה" title="מדריך הכלים"><img alt=""><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"><path d="M6 9l6 6 6-6"/></svg></button><section class="panel" hidden role="dialog" aria-label="מדריך הכלים של MAHALCO" dir="rtl"><div class="header"><span class="art mini"><img alt=""></span><div><strong>לאן מתקדמים?</strong><small>מדריך הכלים של MAHALCO</small></div><button class="close" aria-label="סגירה">×</button></div><div class="messages" role="log" aria-live="polite" aria-relevant="additions"></div><div class="footer"><form class="form"><input aria-label="מה תרצו למצוא?" placeholder="למשל: חניה, צמתים או חתכים…" maxlength="300" autocomplete="off"><button type="submit">שליחה</button></form><p class="status" role="status"></p><div class="tools"><button class="voice panel-voice" aria-label="חיפוש קולי בעברית">חיפוש קולי</button><button class="read" aria-pressed="false">הקראה: כבויה</button><button class="reset">שיחה חדשה</button><button class="motion" aria-pressed="true">אנימציה: פעילה</button><button class="position">איפוס מיקום</button><button class="hide">החזרת המכונית למעלה</button></div></div></section>`;
  const $ = s => root.querySelector(s);
  const faceMarkup = `<svg class="face" viewBox="0 0 1254 1254" aria-hidden="true"><g fill="#fff0b8"><path d="M584 415l14-17h34v10h-27l-12 14zM803 400l14-12h25l16 18-9 8-14-15h-15l-11 10z"/></g><g class="eye"><rect x="595" y="451" width="75" height="109" rx="32" fill="#fff0b8"/><g class="pupil"><rect x="622" y="476" width="35" height="61" rx="16" fill="#23272c"/><rect x="644" y="478" width="10" height="13" rx="2" fill="#fff"/></g></g><g class="eye"><rect x="799" y="441" width="73" height="109" rx="31" fill="#fff0b8"/><g class="pupil"><rect x="813" y="465" width="35" height="61" rx="16" fill="#23272c"/><rect x="836" y="467" width="10" height="13" rx="2" fill="#fff"/></g></g></svg>`;
  root.querySelectorAll('.art').forEach(art=>art.insertAdjacentHTML('beforeend',faceMarkup));
  root.querySelectorAll('img').forEach(img => img.src = new URL('assets/car-guide/car-eyes-base.png',base).href);
  const panel=$('.panel'), input=$('input'), log=$('.messages'), car=$('.car');
  let catalog=[], catalogFailed=false, listening=false, recognition, read=false, lastReply='', moved=false;
  const catalogReady=fetch(new URL('assets/car-guide/catalog.json',base)).then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{catalog=data}).catch(()=>{catalogFailed=true});
  const storage={get(k){try{return localStorage.getItem('mh-car-'+k)}catch{return null}},set(k,v){try{localStorage.setItem('mh-car-'+k,v)}catch{}}};
  let reactionUntil=0;
  function react(){reactionUntil=performance.now()+900}
  const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
  let motionEnabled=storage.get('motion')!=='off';
  function syncMotion(){const active=motionEnabled&&!reducedMotion.matches;host.classList.toggle('motion-off',!active);$('.motion').textContent=reducedMotion.matches?'אנימציה: מופחתת':'אנימציה: '+(active?'פעילה':'כבויה');$('.motion').setAttribute('aria-pressed',String(active));$('.motion').disabled=reducedMotion.matches}
  $('.motion').onclick=()=>{motionEnabled=!motionEnabled;storage.set('motion',motionEnabled?'on':'off');syncMotion()};reducedMotion.addEventListener('change',syncMotion);syncMotion();
  function place(x,y){const w=host.offsetWidth||136,h=host.offsetHeight||158;host.style.left=Math.max(8,Math.min(innerWidth-w-8,x))+'px';host.style.top=Math.max(8,Math.min(innerHeight-h-8,y))+'px';host.style.bottom='auto';positionPanel()}
  function positionPanel(){if(panel.hidden)return;const r=host.getBoundingClientRect(),w=panel.offsetWidth,h=panel.offsetHeight;panel.style.left=Math.max(12,Math.min(innerWidth-w-12,r.right+w+24<=innerWidth?r.right+12:r.left-w-12))+'px';panel.style.top=Math.max(12,Math.min(innerHeight-h-12,r.bottom-h))+'px'}
  function savePosition(){const r=host.getBoundingClientRect();storage.set('position',JSON.stringify({x:r.left,y:r.top}))}
  function open(){if(host.classList.contains('parked')){unpark();return}if(panel.hidden)react();panel.hidden=false;$('.chat').setAttribute('aria-expanded','true');positionPanel();input.focus()}
  function close(){panel.hidden=true;$('.chat').setAttribute('aria-expanded','false');stopVoice();if('speechSynthesis'in window)speechSynthesis.cancel();host.classList.remove('car-speaking');park()}
  // Parked = hidden as a small tab at the top edge. The car only drops down when called.
  function park(){const hadFocus=root.activeElement!==null;$('.dock').hidden=true;$('.restore').hidden=false;host.classList.add('parked');host.style.top='0px';host.style.bottom='auto';host.style.left='8px';if(hadFocus)$('.restore').focus()}
  function unpark(){host.classList.remove('parked');$('.restore').hidden=true;const dock=$('.dock');dock.hidden=false;dock.classList.remove('drop');void dock.offsetWidth;dock.classList.add('drop');let p=null;try{p=JSON.parse(storage.get('position'))}catch{}if(p&&Number.isFinite(p.x)&&Number.isFinite(p.y))place(p.x,p.y);else place(20,innerHeight-190);open()}
  function bubble(text,user=false){const el=document.createElement('div');el.className='bubble'+(user?' user':'');el.textContent=text;log.append(el);while(log.children.length>30)log.firstChild.remove();log.scrollTop=log.scrollHeight;return el}
  function speak(text){if(!read||!('speechSynthesis'in window))return;speechSynthesis.cancel();host.classList.remove('car-speaking');const u=new SpeechSynthesisUtterance(text);u.lang='he-IL';u.onstart=()=>host.classList.add('car-speaking');u.onend=u.onerror=()=>host.classList.remove('car-speaking');speechSynthesis.speak(u)}
  function welcome(){log.replaceChildren();const el=bubble('שלום! אני כאן כדי לעזור למצוא את הכלי המתאים באתר. מה תרצו לתכנן או לבדוק?');const quick=document.createElement('div');quick.className='quick';['חניה','צמתים','חתכים','מרחק ראייה'].forEach(t=>{const b=document.createElement('button');b.textContent=t;b.onclick=()=>ask(t);quick.append(b)});el.append(quick)}
  const normalize=s=>s.toLowerCase().replace(/[״"׳'?,.!؟]/g,' ').replace(/\s+/g,' ').trim();
  async function ask(text){text=text.trim().slice(0,300);if(!text)return;bubble(text,true);input.value='';await catalogReady;
    const words=normalize(text).split(' ').filter(w=>w.length>1&&!['אני','צריך','צריכה','רוצה','של','את','לי','איך','איפה','אפשר','למצוא','כלי','שלום','היי'].includes(w));
    const matches=catalog.map(item=>{const hay=normalize(item.title+' '+item.description+' '+(item.keywords||''));return{...item,score:words.reduce((sum,w)=>sum+((hay.includes(w)||(w.length>3&&/^[לבמהו]/.test(w)&&hay.includes(w.slice(1))))?(normalize(item.title).includes(w)?3:1):0),0)}}).filter(i=>i.score>0).sort((a,b)=>b.score-a.score).slice(0,4);
    lastReply=matches.length?'מצאתי כלים שיכולים להתאים. בחרו כלי כדי לפתוח אותו:':catalogFailed?'לא הצלחתי לטעון את רשימת הכלים. אפשר לפתוח את הקטלוג או לנסות שוב לאחר רענון.':'לא מצאתי התאמה. נסו מונח כמו חניה, צומת, חתך, תור או ראייה.';
    const el=bubble(lastReply), links=document.createElement('div');links.className='results';
    (matches.length?matches:[{title:'פתיחת קטלוג הכלים',description:'כל כלי MAHALCO במקום אחד',url:'index.html#catalog'}]).forEach(item=>{const a=document.createElement('a');a.className='result';const url=new URL(item.url,base);if(!['http:','https:'].includes(url.protocol))return;a.href=url.href;const b=document.createElement('b'),s=document.createElement('span');b.textContent=item.title;s.textContent=item.description;a.append(b,s);links.append(a)});el.append(links);log.scrollTop=log.scrollHeight;react();speak(lastReply+(matches.length?' '+matches.map(m=>m.title).join('. '):''))}
  $('.form').onsubmit=e=>{e.preventDefault();ask(input.value)};$('.chat').onclick=()=>panel.hidden?open():close();$('.close').onclick=close;
  $('.reset').onclick=()=>{if('speechSynthesis'in window)speechSynthesis.cancel();host.classList.remove('car-speaking');stopVoice();welcome();input.focus()};$('.position').onclick=()=>{place(20,innerHeight-190);savePosition()};
  $('.hide').onclick=close;$('.dock').addEventListener('animationend',()=>$('.dock').classList.remove('drop'));
  $('.restore').onclick=unpark;
  park();
  // Pages can call the car: MahalcoCarGuide.open(), or any element with data-car-guide.
  window.MahalcoCarGuide={open,close};
  document.addEventListener('click',e=>{const t=e.target.closest&&e.target.closest('[data-car-guide]');if(t){e.preventDefault();open()}});
  $('.read').onclick=()=>{if(!('speechSynthesis'in window)){$('.status').textContent='הדפדפן אינו תומך בהקראה.';return}read=!read;$('.read').textContent='הקראה: '+(read?'פעילה':'כבויה');$('.read').setAttribute('aria-pressed',String(read));if(read)speak(lastReply||'שלום, מה תרצו למצוא?');else speechSynthesis.cancel()};
  function stopVoice(){if(recognition)recognition.abort();listening=false;host.classList.remove('car-listening');root.querySelectorAll('.voice').forEach(b=>{b.classList.remove('listening');b.setAttribute('aria-label','חיפוש קולי בעברית')})}
  function toggleVoice(){open();if(listening){stopVoice();$('.status').textContent='ההאזנה הופסקה.';return}const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech){$('.status').textContent='חיפוש קולי אינו נתמך בדפדפן זה. אפשר להקליד כאן.';return}recognition=new Speech();recognition.lang='he-IL';recognition.interimResults=false;recognition.maxAlternatives=1;recognition.onstart=()=>{listening=true;host.classList.add('car-listening');root.querySelectorAll('.voice').forEach(b=>{b.classList.add('listening');b.setAttribute('aria-label','הפסקת האזנה')});$('.status').textContent='מקשיב… הדיבור מעובד בשירות הזיהוי של הדפדפן.'};recognition.onresult=e=>{const t=e.results[0][0].transcript;input.value=t;$('.status').textContent='הטקסט מוכן. לחצו שליחה לחיפוש.';input.focus()};recognition.onerror=e=>{$('.status').textContent=e.error==='not-allowed'?'אין הרשאה למיקרופון. אפשר להקליד או לאפשר גישה בדפדפן.':e.error==='aborted'?'ההאזנה הופסקה.':'לא הצלחתי לשמוע. נסו שוב או הקלידו.'};recognition.onend=()=>{listening=false;host.classList.remove('car-listening');root.querySelectorAll('.voice').forEach(b=>{b.classList.remove('listening');b.setAttribute('aria-label','חיפוש קולי בעברית')})};try{recognition.start()}catch{$('.status').textContent='לא ניתן להפעיל את המיקרופון. אפשר להקליד.'}};
  root.querySelectorAll('.voice').forEach(b=>b.onclick=toggleVoice);
  let drag=null, pendingPosition=null, dragLean=0;
  car.onpointerdown=e=>{if(e.button!==0||drag)return;const r=host.getBoundingClientRect();drag={id:e.pointerId,x:e.clientX,y:e.clientY,left:r.left,top:r.top,lastX:e.clientX,lastTime:performance.now()};moved=false;car.setPointerCapture(e.pointerId)};
  car.onpointermove=e=>{if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>5)moved=true;if(moved){const now=performance.now();dragLean=Math.max(-5,Math.min(5,(e.clientX-drag.lastX)/Math.max(8,now-drag.lastTime)*3));drag.lastX=e.clientX;drag.lastTime=now;host.classList.add('car-dragging');pendingPosition={x:drag.left+dx,y:drag.top+dy}}};
  function finishDrag(e){if(!drag||e.pointerId!==drag.id)return;if(pendingPosition){place(pendingPosition.x,pendingPosition.y);pendingPosition=null}host.classList.remove('car-dragging');dragLean=0;if(moved)savePosition();drag=null;if(e.type!=='pointerup')moved=true}
  car.onpointerup=finishDrag;car.onpointercancel=finishDrag;car.onlostpointercapture=finishDrag;
  car.onclick=()=>{if(!moved)panel.hidden?open():close();moved=false};car.onkeydown=e=>{const directions={ArrowLeft:[-20,0],ArrowRight:[20,0],ArrowUp:[0,-20],ArrowDown:[0,20]};if(directions[e.key]){e.preventDefault();const r=host.getBoundingClientRect(),d=directions[e.key];place(r.left+d[0],r.top+d[1]);savePosition()}};
  // Blend poses rather than restarting separate CSS loops on every state change.
  let frame=0,lastFrame=0,poseY=0,poseLean=0,gazeX=0,gazeY=0,pointer=null,nextBlink=performance.now()+2800,blinkStart=0;
  window.addEventListener('pointermove',e=>{if(e.pointerType!=='touch')pointer={x:e.clientX,y:e.clientY}},{passive:true});
  document.documentElement.addEventListener('pointerleave',()=>{pointer=null});
  const arts=[...root.querySelectorAll('.art')];
  function animate(now){frame=0;if(document.hidden)return;const dt=Math.min(50,now-(lastFrame||now));lastFrame=now;const mix=1-Math.exp(-dt/95);const active=motionEnabled&&!reducedMotion.matches;
    if(pendingPosition){place(pendingPosition.x,pendingPosition.y);pendingPosition=null}
    const t=now/1000,isDragging=!!drag&&moved,speaking=host.classList.contains('car-speaking');
    let targetY=-1.4+Math.sin(t*1.8)*1.4,targetLean=Math.sin(t*1.3)*.6;
    if(listening){targetY=-2+Math.sin(t*2.5)*.8;targetLean=-2+Math.sin(t*1.8)*.5}
    if(speaking){targetY=-1.5+Math.sin(t*9)*.8;targetLean=Math.sin(t*5)*.8}
    if(reactionUntil>now&&!listening&&!speaking){targetY-=Math.sin((1-(reactionUntil-now)/900)*Math.PI)*3}
    if(isDragging){targetY=-3;targetLean=dragLean}
    poseY+=(targetY-poseY)*mix;poseLean+=(targetLean-poseLean)*mix;
    const r=car.getBoundingClientRect(),px=pointer?Math.max(-13,Math.min(13,(pointer.x-r.left-r.width/2)*.045)):0,py=pointer?Math.max(-10,Math.min(10,(pointer.y-r.top-r.height/2)*.045)):0;
    gazeX+=(px-gazeX)*mix;gazeY+=(py-gazeY)*mix;
    if(now>=nextBlink&&!blinkStart){blinkStart=now;nextBlink=now+3800+Math.random()*2200}
    let eyeOpen=1;if(blinkStart){const progress=(now-blinkStart)/180;if(progress>=1)blinkStart=0;else eyeOpen=Math.max(.06,Math.abs(progress*2-1))}
    for(const art of arts){art.style.setProperty('--car-y',active?poseY.toFixed(3)+'px':'0px');art.style.setProperty('--car-lean',active?poseLean.toFixed(3)+'deg':'0deg');art.style.setProperty('--eye-open',active?String(eyeOpen):'1');art.style.setProperty('--gaze-x',active?gazeX.toFixed(2)+'px':'0px');art.style.setProperty('--gaze-y',active?gazeY.toFixed(2)+'px':'0px')}
    frame=requestAnimationFrame(animate)
  }
  document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(frame);frame=0;pointer=null;if(drag)finishDrag({pointerId:drag.id,type:'pointercancel'})}else{lastFrame=0;nextBlink=performance.now()+2800;if(!frame)frame=requestAnimationFrame(animate)}});
  frame=requestAnimationFrame(animate);
  root.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden){e.preventDefault();close()}});window.addEventListener('resize',()=>{if(host.classList.contains('parked'))return;const r=host.getBoundingClientRect();place(r.left,r.top)});welcome();
})();
